Control DataFrame visual size

In [1]:
%%html
<style>
/* Any CSS style can go in here. */
.dataframe th {
    font-size: 20px;
}
.dataframe td {
    font-size: 20px;
}
</style>

In [2]:
import numpy as np
import pandas as pd
from pieces import *
from game_logic import *

game_logic

To code:

    check forces move out of check
    - switch last move feature to live in board object
        checkmate
        - make sure working
    en pessaant?

    convert to .py and run games in terminal

    move syntax conversion

In [3]:
piece_dict = {'b_king':'♔', 
                'b_queen': '♕', 
                'b_rook': '♖', 
                'b_bishop':'♗', 
                'b_knight' : '♘', 
                'b_pawn':'♙', 
                'w_king': '♚',
                'w_queen': '♛',
                'w_rook':'♜', 
                'w_bishop':'♝', 
                'w_knight': '♞',
                'w_pawn' : '♟' ,
                '':''}
        
def switch_piece_format(square):
    return piece_dict[str(square)]

In [4]:
K1 = knight('b')

In [5]:
type(new_game.get_square(6,4))

NameError: name 'new_game' is not defined

In [6]:
new_game = game()

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:44: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99

In [7]:
new_game.board

   A  B  C  D  E  F  G  H
8  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
7  ♙  ♙  ♙  ♙  ♙  ♙  ♙  ♙
6
5
4
3
2  ♟  ♟  ♟  ♟  ♟  ♟  ♟  ♟
1  ♜  ♞  ♝  ♛  ♚  ♝  ♞  ♜

In [8]:
print(new_game.board.get_attacks('b'))

{(3, 7), (5, 7), (1, 6), (0, 8), (2, 8), (7, 7), (6, 8), (4, 8), (3, 6), (0, 7), (2, 7), (1, 8), (6, 7), (4, 7), (3, 8), (5, 8), (1, 7), (6, 6), (7, 8)}

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:55: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return self.loc[y][x]

In [9]:
# new_game.get_moves(5,3, show = True)

In [10]:
board_to_grid('D7')

(4, 7)

In [12]:
new_game.move('E2','E4')
display(new_game.board)

('E2',)
('E2',)

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:55: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return self.loc[y][x]

TypeError: pawn.find_moves() missing 1 required positional argument: 'y'

In [32]:
new_game.move(4,2,4,4)
display(new_game.board)

piece =
[]
invalid move

   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙     ♙  ♙  ♙  ♙
3
4           ♙
5           ♟
6
7  ♟  ♟  ♟     ♟  ♟  ♟  ♟
8  ♜  ♞  ♝  ♛  ♚  ♝  ♞  ♜

In [33]:
new_game.board.last_move

(4, 2, 4, 4)

In [34]:
new_game.move(4,7,7,4)
display(new_game.board)

piece =
[]
invalid move

   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙     ♙  ♙  ♙  ♙
3
4           ♙
5           ♟
6
7  ♟  ♟  ♟     ♟  ♟  ♟  ♟
8  ♜  ♞  ♝  ♛  ♚  ♝  ♞  ♜

In [35]:
new_game.move(2,8,3,6)
display(new_game.board)

piece =  ♞
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙     ♙  ♙  ♙  ♙
3
4           ♙
5           ♟
6        ♞
7  ♟  ♟  ♟     ♟  ♟  ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 41♕
[(5, 1), (3, 1), (4, 2), (4, 3), (4, 4), (5, 2), (3, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 52♙
[(6, 3), (4, 3)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
checking attacks 44♙
[(5, 5), (3, 5)]
move checking:  3 6
look_for_checks {(4, 3), (3, 1), (5, 1), (8, 3), (8, 6), (2, 2), (1, 3), (6, 2), (7, 1), (4, 2), (3, 3), (5, 3), (8, 2), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (3, 5), (5, 2), (4, 4), (5, 5), (2, 3), (7, 2), (7, 5), (6, 3)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙     ♙  ♙  ♙  ♙
3
4           ♙
5           ♟
6
7  ♟  ♟  ♟  ♞  ♟  ♟  ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 41♕
[(5, 1), (3, 1), (4, 2), (4, 3), (4, 4), (5, 2), (3, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 52♙
[(6, 3), (4, 3)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
checking attacks 44♙
[(5, 5), (3, 5)]
move checking:  4 7
look_for_checks {(4, 3), (3, 1), (5, 1), (8, 3), (8, 6), (2, 2), (1, 3), (6, 2), (7, 1), (4, 2), (3, 3), (5, 3), (8, 2), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (3, 5), (5, 2), (4, 4), (5, 5), (2, 3), (7, 2), (7, 5), (6, 3)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙     ♙  ♙  ♙  ♙
3
4           ♙
5           ♟
6  ♞
7  ♟  ♟  ♟     ♟  ♟  ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 41♕
[(5, 1), (3, 1), (4, 2), (4, 3), (4, 4), (5, 2), (3, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 52♙
[(6, 3), (4, 3)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
checking attacks 44♙
[(5, 5), (3, 5)]
move checking:  1 6
look_for_checks {(4, 3), (3, 1), (5, 1), (8, 3), (8, 6), (2, 2), (1, 3), (6, 2), (7, 1), (4, 2), (3, 3), (5, 3), (8, 2), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (3, 5), (5, 2), (4, 4), (5, 5), (2, 3), (7, 2), (7, 5), (6, 3)}
[(3, 6), (4, 7), (1, 6)]
valid move
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 36♞
[(4, 8), (5, 7), (4, 4), (1, 7), (2, 8), (5, 5), (2, 4), (1, 5)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 57♟
[(6, 6), (4, 6)]
checking attacks 67♟
[(7, 6), (5, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99

   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙     ♙  ♙  ♙  ♙
3
4           ♙
5           ♟
6        ♞
7  ♟  ♟  ♟     ♟  ♟  ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜

In [37]:
new_game.move(5,2,5,4)
display(new_game.board)

piece =
[]
invalid move

   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♙  ♙
5           ♟
6        ♞
7  ♟  ♟  ♟     ♟  ♟  ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜

In [38]:
new_game.move(3,6,4,4)
display(new_game.board)

piece =  ♞
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞  ♙
5           ♟
6
7  ♟  ♟  ♟     ♟  ♟  ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 41♕
[(5, 1), (3, 1), (4, 2), (4, 3), (4, 4), (5, 2), (6, 3), (7, 4), (8, 5), (3, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2), (4, 3), (3, 4), (2, 5), (1, 6)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
checking attacks 54♙
[(6, 5), (4, 5)]
move checking:  4 4
look_for_checks {(3, 4), (4, 3), (3, 1), (5, 1), (8, 3), (8, 6), (2, 2), (1, 6), (2, 5), (1, 3), (7, 4), (6, 2), (7, 1), (6, 5), (4, 2), (4, 5), (3, 3), (5, 3), (8, 2), (8, 5), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (5, 2), (4, 4), (2, 3), (7, 2), (7, 5), (6, 3)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♙  ♙
5           ♟
6
7  ♟  ♟  ♟     ♟  ♟  ♟  ♟
8  ♜  ♞  ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 41♕
[(5, 1), (3, 1), (4, 2), (4, 3), (4, 4), (5, 2), (6, 3), (7, 4), (8, 5), (3, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2), (4, 3), (3, 4), (2, 5), (1, 6)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
checking attacks 44♙
[(5, 5), (3, 5)]
checking attacks 54♙
[(6, 5), (4, 5)]
move checking:  2 8
look_for_checks {(3, 4), (4, 3), (3, 1), (5, 1), (8, 3), (8, 6), (2, 2), (1, 6), (2, 5), (1, 3), (7, 4), (6, 2), (7, 1), (6, 5), (4, 2), (4, 5), (3, 3), (5, 3), (8, 2), (8, 5), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (3, 5), (5, 2), (4, 4), (5, 5), (2, 3), (7, 2), (7, 5), (6, 3)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♙  ♙
5           ♟  ♞
6
7  ♟  ♟  ♟     ♟  ♟  ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 41♕
[(5, 1), (3, 1), (4, 2), (4, 3), (4, 4), (5, 2), (6, 3), (7, 4), (8, 5), (3, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2), (4, 3), (3, 4), (2, 5), (1, 6)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
checking attacks 44♙
[(5, 5), (3, 5)]
checking attacks 54♙
[(6, 5), (4, 5)]
move checking:  5 5
look_for_checks {(3, 4), (4, 3), (3, 1), (5, 1), (8, 3), (8, 6), (2, 2), (1, 6), (2, 5), (1, 3), (7, 4), (6, 2), (7, 1), (6, 5), (4, 2), (4, 5), (3, 3), (5, 3), (8, 2), (8, 5), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (3, 5), (5, 2), (4, 4), (5, 5), (2, 3), (7, 2), (7, 5), (6, 3)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4     ♞     ♙  ♙
5           ♟
6
7  ♟  ♟  ♟     ♟  ♟  ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 41♕
[(5, 1), (3, 1), (4, 2), (4, 3), (4, 4), (5, 2), (6, 3), (7, 4), (8, 5), (3, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2), (4, 3), (3, 4), (2, 5), (1, 6)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
checking attacks 44♙
[(5, 5), (3, 5)]
checking attacks 54♙
[(6, 5), (4, 5)]
move checking:  2 4
look_for_checks {(3, 4), (4, 3), (3, 1), (5, 1), (8, 3), (8, 6), (2, 2), (1, 6), (2, 5), (1, 3), (7, 4), (6, 2), (7, 1), (6, 5), (4, 2), (4, 5), (3, 3), (5, 3), (8, 2), (8, 5), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (3, 5), (5, 2), (4, 4), (5, 5), (2, 3), (7, 2), (7, 5), (6, 3)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♙  ♙
5  ♞        ♟
6
7  ♟  ♟  ♟     ♟  ♟  ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 41♕
[(5, 1), (3, 1), (4, 2), (4, 3), (4, 4), (5, 2), (6, 3), (7, 4), (8, 5), (3, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2), (4, 3), (3, 4), (2, 5), (1, 6)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
checking attacks 44♙
[(5, 5), (3, 5)]
checking attacks 54♙
[(6, 5), (4, 5)]
move checking:  1 5
look_for_checks {(3, 4), (4, 3), (3, 1), (5, 1), (8, 3), (8, 6), (2, 2), (1, 6), (2, 5), (1, 3), (7, 4), (6, 2), (7, 1), (6, 5), (4, 2), (4, 5), (3, 3), (5, 3), (8, 2), (8, 5), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (3, 5), (5, 2), (4, 4), (5, 5), (2, 3), (7, 2), (7, 5), (6, 3)}
[(4, 4), (2, 8), (5, 5), (2, 4), (1, 5)]
valid move
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 57♟
[(6, 6), (4, 6)]
checking attacks 67♟
[(7, 6), (5, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99

   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞  ♙
5           ♟
6
7  ♟  ♟  ♟     ♟  ♟  ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜

In [39]:
new_game.move(5,4,5,5)
display(new_game.board)

piece =  ♙
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞
5           ♙
6
7  ♟  ♟  ♟     ♟  ♟  ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 57♟
[(6, 6), (4, 6)]
checking attacks 67♟
[(7, 6), (5, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]
move checking:  4 5
look_for_checks {(3, 7), (4, 6), (5, 7), (8, 3), (8, 6), (1, 6), (2, 5), (2, 8), (7, 4), (7, 7), (6, 5), (6, 8), (4, 5), (5, 6), (4, 8), (3, 6), (2, 7), (6, 7), (7, 6), (3, 2), (4, 7), (5, 2), (3, 8), (5, 8), (8, 7), (2, 3), (1, 7), (2, 6), (6, 6), (6, 3), (7, 8)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞
5           ♟  ♙
6
7  ♟  ♟  ♟     ♟  ♟  ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 57♟
[(6, 6), (4, 6)]
checking attacks 67♟
[(7, 6), (5, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]
move checking:  5 5
look_for_checks {(3, 4), (3, 7), (5, 4), (4, 6), (5, 7), (8, 3), (8, 6), (1, 6), (2, 5), (2, 8), (7, 4), (7, 7), (6, 5), (6, 8), (4, 5), (5, 6), (4, 8), (3, 6), (2, 7), (6, 7), (7, 6), (3, 2), (4, 7), (5, 2), (3, 8), (5, 8), (8, 7), (2, 3), (1, 7), (2, 6), (6, 6), (6, 3), (7, 8)}
[(4, 5), (5, 5)]
valid move
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 41♕
[(5, 1), (3, 1), (4, 2), (4, 3), (4, 4), (5, 2), (6, 3), (7, 4), (8, 5), (3, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2), (4, 3), (3, 4), (2, 5), (1, 6)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
checking attacks 55♙
[(6, 6), (4, 6)]

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99

   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞
5           ♟  ♙
6
7  ♟  ♟  ♟     ♟  ♟  ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜

In [40]:
new_game.move(6,7,6,5)
display(new_game.board)

piece =  ♟
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞
5           ♟  ♙
6                 ♟
7  ♟  ♟  ♟     ♟     ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 41♕
[(5, 1), (3, 1), (4, 2), (4, 3), (4, 4), (5, 2), (6, 3), (7, 4), (8, 5), (3, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2), (4, 3), (3, 4), (2, 5), (1, 6)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
checking attacks 55♙
[(6, 6), (4, 6)]
move checking:  6 6
look_for_checks {(3, 4), (4, 3), (3, 1), (4, 6), (5, 1), (8, 3), (8, 6), (2, 2), (1, 6), (2, 5), (1, 3), (7, 4), (6, 2), (7, 1), (4, 2), (3, 3), (5, 3), (8, 2), (8, 5), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (5, 2), (4, 4), (2, 3), (7, 2), (6, 6), (7, 5), (6, 3)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞
5           ♟  ♙  ♟
6
7  ♟  ♟  ♟     ♟     ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 41♕
[(5, 1), (3, 1), (4, 2), (4, 3), (4, 4), (5, 2), (6, 3), (7, 4), (8, 5), (3, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2), (4, 3), (3, 4), (2, 5), (1, 6)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
checking attacks 55♙
[(6, 6), (4, 6)]
move checking:  6 5
look_for_checks {(3, 4), (4, 3), (3, 1), (4, 6), (5, 1), (8, 3), (8, 6), (2, 2), (1, 6), (2, 5), (1, 3), (7, 4), (6, 2), (7, 1), (4, 2), (3, 3), (5, 3), (8, 2), (8, 5), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (5, 2), (4, 4), (2, 3), (7, 2), (6, 6), (7, 5), (6, 3)}
[(6, 6), (6, 5)]
valid move
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4), (6, 6)]
checking attacks 65♟
[(7, 4), (5, 4), (6, 6)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 57♟
[(6, 6), (4, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99

   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞
5           ♟  ♙  ♟
6
7  ♟  ♟  ♟     ♟     ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜

In [41]:
print(new_game.board.last_move)
new_game.move(5,5,6,6)
display(new_game.board)

(6, 7, 6, 5)
piece =  ♙
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞
5           ♟     ♟
6              ♙
7  ♟  ♟  ♟     ♟     ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 65♟
[(7, 4), (5, 4)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 57♟
[(6, 6), (4, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]
move checking:  5 6
look_for_checks {(3, 4), (3, 7), (5, 4), (4, 6), (5, 7), (8, 6), (1, 6), (2, 5), (2, 8), (7, 4), (7, 7), (6, 5), (6, 8), (4, 5), (5, 6), (4, 8), (3, 6), (2, 7), (6, 7), (7, 6), (3, 2), (4, 7), (5, 2), (3, 8), (5, 8), (8, 7), (2, 3), (1, 7), (2, 6), (6, 6), (6, 3), (7, 8)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞
5           ♟
6                 ♙
7  ♟  ♟  ♟     ♟     ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 57♟
[(6, 6), (4, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]
move checking:  6 6
look_for_checks {(3, 4), (3, 7), (5, 4), (4, 6), (5, 7), (8, 3), (8, 6), (1, 6), (2, 5), (2, 8), (7, 4), (7, 7), (6, 5), (6, 8), (4, 5), (5, 6), (4, 8), (3, 6), (2, 7), (6, 7), (7, 6), (3, 2), (4, 7), (5, 2), (3, 8), (5, 8), (8, 7), (2, 3), (1, 7), (2, 6), (6, 6), (6, 3), (7, 8)}
[(5, 6), (6, 6)]
valid move
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 41♕
[(5, 1), (3, 1), (4, 2), (4, 3), (4, 4), (5, 2), (6, 3), (7, 4), (8, 5), (3, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2), (4, 3), (3, 4), (2, 5), (1, 6)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
checking attacks 66♙
[(7, 7), (5, 7)]

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99

   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞
5           ♟
6                 ♙
7  ♟  ♟  ♟     ♟     ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜

In [42]:
new_game.move(5,7,6,6)
display(new_game.board)
new_game.move(4,1,5,2)
display(new_game.board)
new_game.move(6,5,6,4)
display(new_game.board)
new_game.get_moves(5,1, True)

piece =  ♟
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞
5           ♟
6                 ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 41♕
[(5, 1), (3, 1), (4, 2), (4, 3), (4, 4), (5, 2), (6, 3), (7, 4), (8, 5), (3, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2), (4, 3), (3, 4), (2, 5), (1, 6)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
move checking:  6 6
look_for_checks {(3, 4), (4, 3), (3, 1), (5, 1), (8, 3), (8, 6), (2, 2), (1, 6), (2, 5), (1, 3), (7, 4), (6, 2), (7, 1), (4, 2), (3, 3), (5, 3), (8, 2), (8, 5), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (5, 2), (4, 4), (2, 3), (7, 2), (7, 5), (6, 3)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞
5           ♟
6              ♟  ♙
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 41♕
[(5, 1), (3, 1), (4, 2), (4, 3), (4, 4), (5, 2), (6, 3), (7, 4), (8, 5), (3, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2), (4, 3), (3, 4), (2, 5), (1, 6)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
checking attacks 66♙
[(7, 7), (5, 7)]
move checking:  5 6
look_for_checks {(3, 4), (4, 3), (3, 1), (5, 1), (5, 7), (8, 3), (8, 6), (2, 2), (1, 6), (2, 5), (1, 3), (7, 4), (6, 2), (7, 1), (7, 7), (4, 2), (3, 3), (5, 3), (8, 2), (8, 5), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (5, 2), (4, 4), (2, 3), (7, 2), (7, 5), (6, 3)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞
5           ♟  ♟
6                 ♙
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 41♕
[(5, 1), (3, 1), (4, 2), (4, 3), (4, 4), (5, 2), (6, 3), (7, 4), (8, 5), (3, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2), (4, 3), (3, 4), (2, 5), (1, 6)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
checking attacks 66♙
[(7, 7), (5, 7)]
move checking:  5 5
look_for_checks {(3, 4), (4, 3), (3, 1), (5, 1), (5, 7), (8, 3), (8, 6), (2, 2), (1, 6), (2, 5), (1, 3), (7, 4), (6, 2), (7, 1), (7, 7), (4, 2), (3, 3), (5, 3), (8, 2), (8, 5), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (5, 2), (4, 4), (2, 3), (7, 2), (7, 5), (6, 3)}
[(6, 6), (5, 6), (5, 5)]
valid move
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 66♟
[(7, 5), (5, 5)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (6, 6), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7), (4, 6), (3, 5), (2, 4), (1, 3)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99

   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞
5           ♟
6                 ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜

piece =  ♕
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗     ♔  ♗  ♘  ♖
2  ♙  ♙  ♙  ♕     ♙  ♙  ♙
3
4           ♞
5           ♟
6                 ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 66♟
[(7, 5), (5, 5)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (6, 6), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7), (4, 6), (3, 5), (2, 4), (1, 3)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]
move checking:  4 2
look_for_checks {(3, 4), (3, 7), (5, 4), (4, 6), (5, 7), (8, 3), (8, 6), (1, 6), (2, 5), (1, 3), (2, 8), (7, 4), (7, 7), (6, 5), (6, 8), (4, 5), (5, 6), (4, 8), (3, 6), (2, 4), (2, 7), (6, 7), (7, 6), (3, 2), (4, 7), (3, 5), (5, 2), (3, 8), (5, 5), (5, 8), (8, 7), (2, 3), (1, 7), (2, 6), (6, 6), (7, 5), (6, 3), (7, 8)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗     ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3           ♕
4           ♞
5           ♟
6                 ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 66♟
[(7, 5), (5, 5)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (6, 6), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7), (4, 6), (3, 5), (2, 4), (1, 3)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]
move checking:  4 3
look_for_checks {(3, 4), (3, 7), (5, 4), (4, 6), (5, 7), (8, 3), (8, 6), (1, 6), (2, 5), (1, 3), (2, 8), (7, 4), (7, 7), (6, 5), (6, 8), (4, 5), (5, 6), (4, 8), (3, 6), (2, 4), (2, 7), (6, 7), (7, 6), (3, 2), (4, 7), (3, 5), (5, 2), (3, 8), (5, 5), (5, 8), (8, 7), (2, 3), (1, 7), (2, 6), (6, 6), (7, 5), (6, 3), (7, 8)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗     ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♕
5           ♟
6                 ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 66♟
[(7, 5), (5, 5)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (6, 6), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7), (4, 6), (3, 5), (2, 4), (1, 3)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]
move checking:  4 4
look_for_checks {(3, 4), (3, 7), (5, 4), (4, 6), (5, 7), (8, 3), (8, 6), (1, 6), (1, 3), (2, 8), (7, 4), (7, 7), (6, 5), (6, 8), (4, 5), (5, 6), (4, 8), (3, 6), (2, 4), (2, 7), (6, 7), (7, 6), (4, 7), (3, 5), (3, 8), (5, 5), (5, 8), (8, 7), (1, 7), (2, 6), (6, 6), (7, 5), (7, 8)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗     ♔  ♗  ♘  ♖
2  ♙  ♙  ♙     ♕  ♙  ♙  ♙
3
4           ♞
5           ♟
6                 ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 66♟
[(7, 5), (5, 5)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (6, 6), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7), (4, 6), (3, 5), (2, 4), (1, 3)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]
move checking:  5 2
look_for_checks {(3, 4), (3, 7), (5, 4), (4, 6), (5, 7), (8, 3), (8, 6), (1, 6), (2, 5), (1, 3), (2, 8), (7, 4), (7, 7), (6, 5), (6, 8), (4, 5), (5, 6), (4, 8), (3, 6), (2, 4), (2, 7), (6, 7), (7, 6), (3, 2), (4, 7), (3, 5), (5, 2), (3, 8), (5, 5), (5, 8), (8, 7), (2, 3), (1, 7), (2, 6), (6, 6), (7, 5), (6, 3), (7, 8)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗     ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3                 ♕
4           ♞
5           ♟
6                 ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 66♟
[(7, 5), (5, 5)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (6, 6), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7), (4, 6), (3, 5), (2, 4), (1, 3)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]
move checking:  6 3
look_for_checks {(3, 4), (3, 7), (5, 4), (4, 6), (5, 7), (8, 3), (8, 6), (1, 6), (2, 5), (1, 3), (2, 8), (7, 4), (7, 7), (6, 5), (6, 8), (4, 5), (5, 6), (4, 8), (3, 6), (2, 4), (2, 7), (6, 7), (7, 6), (3, 2), (4, 7), (3, 5), (5, 2), (3, 8), (5, 5), (5, 8), (8, 7), (2, 3), (1, 7), (2, 6), (6, 6), (7, 5), (6, 3), (7, 8)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗     ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞        ♕
5           ♟
6                 ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 66♟
[(7, 5), (5, 5)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (6, 6), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7), (4, 6), (3, 5), (2, 4), (1, 3)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]
move checking:  7 4
look_for_checks {(3, 4), (3, 7), (5, 4), (4, 6), (5, 7), (8, 6), (1, 6), (2, 5), (1, 3), (2, 8), (7, 4), (7, 7), (6, 5), (6, 8), (4, 5), (5, 6), (4, 8), (3, 6), (2, 4), (2, 7), (6, 7), (7, 6), (3, 2), (4, 7), (3, 5), (5, 2), (3, 8), (5, 5), (5, 8), (8, 7), (2, 3), (1, 7), (2, 6), (6, 6), (7, 5), (6, 3), (7, 8)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗     ♔  ♗  ♘  ♖
2  ♙  ♙  ♙        ♙  ♙  ♙
3
4           ♞
5           ♟           ♕
6                 ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 66♟
[(7, 5), (5, 5)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (6, 6), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7), (4, 6), (3, 5), (2, 4), (1, 3)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]
move checking:  8 5
look_for_checks {(3, 4), (3, 7), (5, 4), (4, 6), (5, 7), (8, 3), (8, 6), (1, 6), (2, 5), (1, 3), (2, 8), (7, 4), (7, 7), (6, 5), (6, 8), (4, 5), (5, 6), (4, 8), (3, 6), (2, 4), (2, 7), (6, 7), (7, 6), (3, 2), (4, 7), (3, 5), (5, 2), (3, 8), (5, 5), (5, 8), (8, 7), (2, 3), (1, 7), (2, 6), (6, 6), (7, 5), (6, 3), (7, 8)}
[(4, 2), (4, 3), (4, 4), (5, 2), (6, 3), (7, 4), (8, 5)]
valid move
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 52♕
[(6, 2), (4, 2), (3, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 1), (6, 3), (7, 4), (8, 5), (6, 1), (4, 3), (3, 4), (2, 5), (1, 6), (4, 1)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99

   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗     ♔  ♗  ♘  ♖
2  ♙  ♙  ♙     ♕  ♙  ♙  ♙
3
4           ♞
5           ♟
6                 ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜

piece =
[]
invalid move

   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗     ♔  ♗  ♘  ♖
2  ♙  ♙  ♙     ♕  ♙  ♙  ♙
3
4           ♞
5           ♟
6                 ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜

piece =  ♔
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 66♟
[(7, 5), (5, 5)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (6, 6), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7), (4, 6), (3, 5), (2, 4), (1, 3)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  ♔     ♗  ♘  ♖
2  ♙  ♙  ♙     ♕  ♙  ♙  ♙
3
4           ♞
5           ♟
6                 ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 66♟
[(7, 5), (5, 5)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (6, 6), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7), (4, 6), (3, 5), (2, 4), (1, 3)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]
move checking:  4 1
look_for_checks {(3, 4), (3, 7), (5, 4), (4, 6), (5, 7), (8, 3), (8, 6), (1, 6), (2, 5), (1, 3), (2, 8), (7, 4), (7, 7), (6, 5), (6, 8), (4, 5), (5, 6), (4, 8), (3, 6), (2, 4), (2, 7), (6, 7), (7, 6), (3, 2), (4, 7), (3, 5), (5, 2), (3, 8), (5, 5), (5, 8), (8, 7), (2, 3), (1, 7), (2, 6), (6, 6), (7, 5), (6, 3), (7, 8)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗        ♗  ♘  ♖
2  ♙  ♙  ♙  ♔  ♕  ♙  ♙  ♙
3
4           ♞
5           ♟
6                 ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 66♟
[(7, 5), (5, 5)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (6, 6), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 68♝
[(7, 7), (5, 7), (4, 6), (3, 5), (2, 4), (1, 3)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]
move checking:  4 2
look_for_checks {(3, 4), (3, 7), (5, 4), (4, 6), (5, 7), (8, 3), (8, 6), (1, 6), (2, 5), (1, 3), (2, 8), (7, 4), (7, 7), (6, 5), (6, 8), (4, 5), (5, 6), (4, 8), (3, 6), (2, 4), (2, 7), (6, 7), (7, 6), (3, 2), (4, 7), (3, 5), (5, 2), (3, 8), (5, 5), (5, 8), (8, 7), (2, 3), (1, 7), (2, 6), (6, 6), (7, 5), (6, 3), (7, 8)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗  X  ♔  ♗  ♘  ♖
2  ♙  ♙  ♙  X  ♕  ♙  ♙  ♙
3
4           ♞
5           ♟
6                 ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚  ♝  ♞  ♜

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99

[(4, 1), (4, 2)]

In [43]:
new_game.move(6,8,5,7)
display(new_game.board)
# new_game.get_moves(5,2, True)
# new_game.turn

piece =  ♝
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗     ♔  ♗  ♘  ♖
2  ♙  ♙  ♙     ♕  ♙  ♙  ♙
3
4           ♞
5           ♟
6                 ♟
7  ♟  ♟  ♟     ♝     ♟  ♟
8  ♜     ♝  ♛  ♚     ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 52♕
[(6, 2), (4, 2), (3, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 1), (6, 3), (7, 4), (8, 5), (6, 1), (4, 3), (3, 4), (2, 5), (1, 6), (4, 1)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
move checking:  5 7
look_for_checks {(3, 4), (4, 3), (5, 4), (5, 1), (5, 7), (8, 3), (8, 6), (2, 2), (1, 6), (2, 5), (1, 3), (7, 4), (6, 2), (7, 1), (4, 2), (3, 3), (5, 6), (5, 3), (8, 2), (8, 5), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (5, 2), (5, 5), (2, 3), (7, 2), (7, 5), (6, 3)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗     ♔  ♗  ♘  ♖
2  ♙  ♙  ♙     ♕  ♙  ♙  ♙
3
4           ♞
5           ♟
6           ♝     ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚     ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 52♕
[(6, 2), (4, 2), (3, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 1), (6, 3), (7, 4), (8, 5), (6, 1), (4, 3), (3, 4), (2, 5), (1, 6), (4, 1)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
move checking:  4 6
look_for_checks {(3, 4), (4, 3), (5, 4), (5, 1), (5, 7), (8, 3), (8, 6), (2, 2), (1, 6), (2, 5), (1, 3), (7, 4), (6, 2), (7, 1), (4, 2), (3, 3), (5, 6), (5, 3), (8, 2), (8, 5), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (5, 2), (5, 5), (5, 8), (2, 3), (7, 2), (7, 5), (6, 3)}
   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗     ♔  ♗  ♘  ♖
2  ♙  ♙  ♙     ♕  ♙  ♙  ♙
3
4     ♝     ♞
5           ♟
6                 ♟
7  ♟  ♟  ♟           ♟  ♟
8  ♜     ♝  ♛  ♚     ♞  ♜
checking attacks 11♖
[(2, 1), (1, 2)]
checking attacks 21♘
[(3, 3), (4, 2), (1, 3)]
checking attacks 31♗
[(4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (2, 2)]
checking attacks 51♔
[(6, 1), (4, 1), (5, 2), (6, 2), (4, 2)]
checking attacks 61♗
[(7, 2), (5, 2)]
checking attacks 71♘
[(8, 3), (5, 2), (6, 3)]
checking attacks 81♖
[(7, 1), (8, 2)]
checking attacks 12♙
[(2, 3)]
checking attacks 22♙
[(3, 3), (1, 3)]
checking attacks 32♙
[(4, 3), (2, 3)]
checking attacks 52♕
[(6, 2), (4, 2), (3, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 1), (6, 3), (7, 4), (8, 5), (6, 1), (4, 3), (3, 4), (2, 5), (1, 6), (4, 1)]
checking attacks 62♙
[(7, 3), (5, 3)]
checking attacks 72♙
[(8, 3), (6, 3)]
checking attacks 82♙
[(7, 3)]
move checking:  2 4
look_for_checks {(3, 4), (4, 3), (5, 4), (5, 1), (5, 7), (8, 3), (8, 6), (2, 2), (1, 6), (2, 5), (1, 3), (7, 4), (6, 2), (7, 1), (4, 2), (3, 3), (5, 6), (5, 3), (8, 2), (8, 5), (1, 2), (2, 1), (6, 1), (6, 4), (7, 3), (3, 2), (4, 1), (5, 2), (5, 5), (5, 8), (2, 3), (7, 2), (7, 5), (6, 3)}
[(5, 7), (3, 5), (1, 3)]
valid move
checking attacks 44♞
[(5, 6), (6, 5), (5, 2), (2, 5), (3, 6), (6, 3), (3, 2), (2, 3)]
checking attacks 45♟
[(5, 4), (3, 4)]
checking attacks 66♟
[(7, 5), (5, 5)]
checking attacks 17♟
[(2, 6)]
checking attacks 27♟
[(3, 6), (1, 6)]
checking attacks 37♟
[(4, 6), (2, 6)]
checking attacks 57♝
[(6, 8), (6, 6), (4, 8), (4, 6), (3, 5), (2, 4), (1, 3)]
checking attacks 77♟
[(8, 6), (6, 6)]
checking attacks 87♟
[(7, 6)]
checking attacks 18♜
[(2, 8), (3, 8), (1, 7)]
checking attacks 38♝
[(4, 7), (5, 6), (6, 5), (7, 4), (8, 3), (2, 7)]
checking attacks 48♛
[(5, 8), (3, 8), (4, 7), (4, 6), (4, 5), (5, 7), (3, 7)]
checking attacks 58♚
[(6, 8), (4, 8), (5, 7), (6, 7), (4, 7)]
checking attacks 78♞
[(8, 6), (6, 6), (5, 7)]
checking attacks 88♜
[(7, 8), (8, 7)]

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:24: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = -99, -99, -99, -99

   1  2  3  4  5  6  7  8
1  ♖  ♘  ♗     ♔  ♗  ♘  ♖
2  ♙  ♙  ♙     ♕  ♙  ♙  ♙
3
4           ♞
5           ♟
6                 ♟
7  ♟  ♟  ♟     ♝     ♟  ♟
8  ♜     ♝  ♛  ♚     ♞  ♜

In [144]:
board = pd.DataFrame(columns=[1,2,3,4,5,6,7,8], index=reversed(range(8)))
print(board)

     1    2    3    4    5    6    7    8
7  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN