Control DataFrame visual size

In [1]:
%%html
<style>
/* Any CSS style can go in here. */
.dataframe th {
    font-size: 20px;
}
.dataframe td {
    font-size: 20px;
}
</style>

In [2]:
import numpy as np
import pandas as pd
from pieces import *
from game_logic import *

game_logic

To code:

    check forces move out of check
    - switch last move feature to live in board object
        checkmate
        - make sure working
    en pessaant?

    convert to .py and run games in terminal

    move syntax conversion

In [3]:
piece_dict = {'b_king':'♔', 
                'b_queen': '♕', 
                'b_rook': '♖', 
                'b_bishop':'♗', 
                'b_knight' : '♘', 
                'b_pawn':'♙', 
                'w_king': '♚',
                'w_queen': '♛',
                'w_rook':'♜', 
                'w_bishop':'♝', 
                'w_knight': '♞',
                'w_pawn' : '♟' ,
                '':''}
        
def switch_piece_format(square):
    return piece_dict[str(square)]

In [4]:
K1 = knight('b')

In [5]:
new_game = game()

In [6]:
new_game.board
new_game.execute_move_list([
    ('e2', 'e4'),
    ('d7', 'd5'),
    ('b1', 'c3'),
    ('d5', 'e4'),
    ('c3', 'e4'),
    ('e7', 'e5'),
    ('d2', 'd4'),
    ('e5', 'd4'),
    ('c2', 'c4'),
    ('d4', 'c3'),
    ('d1', 'd8')
])
new_game.board

[(5, 3), (5, 4)]
[(5, 3), (5, 4)]
[(4, 6), (4, 5)]
[(4, 6), (4, 5)]
[(3, 3), (1, 3)]
[(3, 3), (1, 3)]
[(5, 4), (4, 4)]
[(5, 4), (4, 4)]
[(4, 5), (5, 4), (1, 4), (2, 5), (5, 2), (2, 1)]
[(4, 5), (5, 4), (1, 4), (2, 5), (5, 2), (2, 1)]
[(5, 6), (5, 5)]
[(5, 6), (5, 5)]
[(4, 3), (4, 4)]
[(4, 3), (4, 4)]
[(4, 4)]
[(4, 4)]
[(3, 3), (3, 4)]
[(3, 3), (3, 4)]
[(4, 3), (3, 3)]
[(4, 3), (3, 3)]
[(4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (5, 2), (6, 3), (7, 4), (8, 5), (3, 2), (2, 3), (1, 4)]
[(4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (5, 2), (6, 3), (7, 4), (8, 5), (3, 2), (2, 3), (1, 4)]

   a  b  c  d  e  f  g  h
8  ♖  ♘  ♗  ♛  ♔  ♗  ♘  ♖
7  ♙  ♙  ♙        ♙  ♙  ♙
6
5
4              ♞
3        ♙
2  ♟  ♟           ♟  ♟  ♟
1  ♜     ♝     ♚  ♝  ♞  ♜

In [8]:
print(new_game.board.last_move)
print(new_game.status)
new_game.move('e8', 'f7')
display(new_game.board)

('d1', 'd8')
check
[(4, 8)]
[(4, 8)]
invalid move

   a  b  c  d  e  f  g  h
8  ♖  ♘  ♗  ♛  ♔  ♗  ♘  ♖
7  ♙  ♙  ♙        ♙  ♙  ♙
6
5
4              ♞
3        ♙
2  ♟  ♟           ♟  ♟  ♟
1  ♜     ♝     ♚  ♝  ♞  ♜

In [24]:
new_game.move('c2','c4')
display(new_game.board)
new_game.move('d4','c3')
display(new_game.board)
new_game.move('d1', 'd8')
display(new_game.board)
new_game.get_moves('e8', True)

('c2',)
c 2
('c2',)
c 2
pos c2
piece =  ♟
finding moves for  3 2
4 3
(4, 3)

2 3
(2, 3)

3 3
(3, 3)

3 4
(3, 4)

(4, 4)
[(3, 3), (3, 4)]
c3
('c2',)
c 2
('c2',)
c 2
pos1 piece
c2 ♟
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)

8 3
(8, 3)

2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)

4 4
(4, 4)
♙
5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)

2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

5 3
(5, 3)

3 3
(3, 3)
♟
(4, 4)
(3, 7)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(1, 6)
(1, 3)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 5)
(3, 3)
(5, 6)
(4, 8)
(3, 6)
(5, 3)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 7)
(3, 5)
(4, 4)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)
c4
('c2',)
c 2
('c2',)
c 2
pos1 piece
c2 ♟
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)

8 3
(8, 3)

2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)

4 4
(4, 4)
♙
5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)

2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

5 3
(5, 3)

3 3
(3, 3)

(3, 7)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(1, 6)
(1, 3)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 5)
(3, 3)
(5, 6)
(4, 8)
(3, 6)
(5, 3)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 7)
(3, 5)
(4, 4)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)
valid move
('c2',)
c 2
pos1 piece
c2 ♟
4 5
(4, 5)

2 5
(2, 5)

(3, 4)
Knight moves:
5 4
(6, 6)
(7, 5)
(6, 2)
(3, 5)
(4, 6)
(7, 3)
(4, 2)
(3, 3)
2 3
(2, 3)

0 3
(0, 3)
None
(3, 4)
3 3
(3, 3)

1 3
(1, 3)

(3, 4)
7 3
(7, 3)

5 3
(5, 3)

(3, 4)
8 3
(8, 3)

6 3
(6, 3)

(3, 4)
9 3
(9, 3)
None
7 3
(7, 3)

(3, 4)
2 1
(2, 1)

3 1
(3, 1)
♝
1 2
(1, 2)
♟
4 2
(4, 2)

5 3
(5, 3)

6 4
(6, 4)

7 5
(7, 5)

8 6
(8, 6)

2 2
(2, 2)
♟
5 1
(5, 1)
♚
3 1
(3, 1)
♝
4 2
(4, 2)

4 3
(4, 3)

4 4
(4, 4)
♙
(4, 1)
5 2
(5, 2)

6 3
(6, 3)

7 4
(7, 4)

8 5
(8, 5)

3 2
(3, 2)

2 3
(2, 3)

1 4
(1, 4)

6 1
(6, 1)
♝
4 1
(4, 1)
♛
5 2
(5, 2)

5 0
(5, 0)
None
6 2
(6, 2)
♟
6 0
(6, 0)
None
4 2
(4, 2)

4 0
(4, 0)
None
7 2
(7, 2)
♟
5 2
(5, 2)

4 3
(4, 3)

3 4
(3, 4)
♟
Knight moves:
7 1
(8, 3)
(9, 2)
(8, -1)
(5, 2)
(6, 3)
(9, 0)
(6, -1)
(5, 0)
7 1
(7, 1)
♞
8 2
(8, 2)
♟
(3, 4)
(4, 3)
(3, 1)
(4, 6)
(5, 1)
(8, 3)
(8, 6)
(2, 2)
(2, 5)
(1, 3)
(7, 4)
(6, 2)
(7, 1)
(4, 2)
(4, 5)
(3, 3)
(5, 3)
(8, 2)
(8, 5)
(1, 2)
(2, 1)
(6, 1)
(6, 4)
(7, 3)
(3, 2)
(4, 1)
(3, 5)
(5, 2)
(4, 4)
(1, 4)
(2, 3)
(7, 2)
(6, 6)
(7, 5)
(6, 3)

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None

   a  b  c  d  e  f  g  h
8  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
7  ♙  ♙  ♙        ♙  ♙  ♙
6
5
4        ♟  ♙  ♞
3
2  ♟  ♟           ♟  ♟  ♟
1  ♜     ♝  ♛  ♚  ♝  ♞  ♜

('d4',)
d 4
('d4',)
d 4
pos d4
piece =  ♙
finding moves for  4 4
5 3
(5, 3)

3 3
(3, 3)

4 3
(4, 3)

(3, 4)
[(4, 3), (3, 3)]
d3
('d4',)
d 4
('d4',)
d 4
pos1 piece
d4 ♙
4 5
(4, 5)

2 5
(2, 5)

Knight moves:
5 4
(6, 6)
(7, 5)
(6, 2)
(3, 5)
(4, 6)
(7, 3)
(4, 2)
(3, 3)
2 3
(2, 3)

0 3
(0, 3)
None
3 3
(3, 3)

1 3
(1, 3)

7 3
(7, 3)

5 3
(5, 3)

8 3
(8, 3)

6 3
(6, 3)

9 3
(9, 3)
None
7 3
(7, 3)

2 1
(2, 1)

3 1
(3, 1)
♝
1 2
(1, 2)
♟
4 2
(4, 2)

5 3
(5, 3)

6 4
(6, 4)

7 5
(7, 5)

8 6
(8, 6)

2 2
(2, 2)
♟
5 1
(5, 1)
♚
3 1
(3, 1)
♝
4 2
(4, 2)

4 3
(4, 3)
♙
(4, 1)
5 2
(5, 2)

6 3
(6, 3)

7 4
(7, 4)

8 5
(8, 5)

3 2
(3, 2)

2 3
(2, 3)

1 4
(1, 4)

6 1
(6, 1)
♝
4 1
(4, 1)
♛
5 2
(5, 2)

5 0
(5, 0)
None
6 2
(6, 2)
♟
6 0
(6, 0)
None
4 2
(4, 2)

4 0
(4, 0)
None
7 2
(7, 2)
♟
5 2
(5, 2)

4 3
(4, 3)
♙
(6, 1)
Knight moves:
7 1
(8, 3)
(9, 2)
(8, -1)
(5, 2)
(6, 3)
(9, 0)
(6, -1)
(5, 0)
7 1
(7, 1)
♞
8 2
(8, 2)
♟
(4, 3)
(3, 1)
(4, 6)
(5, 1)
(8, 3)
(8, 6)
(2, 2)
(2, 5)
(1, 3)
(7, 4)
(6, 2)
(7, 1)
(4, 2)
(4, 5)
(3, 3)
(5, 3)
(8, 2)
(8, 5)
(1, 2)
(2, 1)
(6, 1)
(6, 4)
(7, 3)
(3, 2)
(4, 1)
(3, 5)
(5, 2)
(1, 4)
(2, 3)
(7, 2)
(6, 6)
(7, 5)
(6, 3)
c3
('d4',)
d 4
('d4',)
d 4
pos1 piece
d4 ♙
('c3',)
c 3
En Pessant Moving
pos2: c3 piece: ♙
pos1: d4
col2: c y2: 3

Knight moves:
5 4
(6, 6)
(7, 5)
(6, 2)
(3, 5)
(4, 6)
(7, 3)
(4, 2)
(3, 3)
2 3
(2, 3)

0 3
(0, 3)
None
3 3
(3, 3)
♙
(2, 2)
1 3
(1, 3)

7 3
(7, 3)

5 3
(5, 3)

8 3
(8, 3)

6 3
(6, 3)

9 3
(9, 3)
None
7 3
(7, 3)

2 1
(2, 1)

3 1
(3, 1)
♝
1 2
(1, 2)
♟
4 2
(4, 2)

5 3
(5, 3)

6 4
(6, 4)

7 5
(7, 5)

8 6
(8, 6)

2 2
(2, 2)
♟
5 1
(5, 1)
♚
3 1
(3, 1)
♝
4 2
(4, 2)

4 3
(4, 3)

4 4
(4, 4)

4 5
(4, 5)

4 6
(4, 6)

4 7
(4, 7)

4 8
(4, 8)
♕
(4, 1)
5 2
(5, 2)

6 3
(6, 3)

7 4
(7, 4)

8 5
(8, 5)

3 2
(3, 2)

2 3
(2, 3)

1 4
(1, 4)

6 1
(6, 1)
♝
4 1
(4, 1)
♛
5 2
(5, 2)

5 0
(5, 0)
None
6 2
(6, 2)
♟
6 0
(6, 0)
None
4 2
(4, 2)

4 0
(4, 0)
None
7 2
(7, 2)
♟
5 2
(5, 2)

4 3
(4, 3)

3 4
(3, 4)

2 5
(2, 5)

1 6
(1, 6)

Knight moves:
7 1
(8, 3)
(9, 2)
(8, -1)
(5, 2)
(6, 3)
(9, 0)
(6, -1)
(5, 0)
7 1
(7, 1)
♞
8 2
(8, 2)
♟
(3, 4)
(4, 3)
(3, 1)
(4, 6)
(5, 1)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(2, 5)
(1, 3)
(7, 4)
(6, 2)
(7, 1)
(4, 2)
(4, 5)
(3, 3)
(4, 8)
(5, 3)
(8, 2)
(8, 5)
(1, 2)
(2, 1)
(6, 1)
(6, 4)
(7, 3)
(3, 2)
(4, 1)
(4, 7)
(3, 5)
(5, 2)
(4, 4)
(1, 4)
(2, 3)
(7, 2)
(6, 6)
(7, 5)
(6, 3)
valid move
('d4',)
d 4
pos1 piece
d4 ♙
('c3',)
c 3
En Pessant Moving
pos2: c3 piece: ♙
pos1: d4
col2: c y2: 3

2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)

8 3
(8, 3)

2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)

4 4
(4, 4)

4 3
(4, 3)

4 2
(4, 2)

4 1
(4, 1)
♛
(4, 8)
5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
(3, 3)
3 6
(3, 6)

1 6
(1, 6)

(3, 3)
4 6
(4, 6)

2 6
(2, 6)

(3, 3)
7 6
(7, 6)

5 6
(5, 6)

(3, 3)
8 6
(8, 6)

6 6
(6, 6)

(3, 3)
9 6
(9, 6)
None
7 6
(7, 6)

(3, 3)
4 2
(4, 2)

2 2
(2, 2)
♟
(3, 3)
(3, 3)
(4, 3)
(3, 7)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(1, 3)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 2)
(4, 5)
(5, 6)
(4, 8)
(3, 6)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 1)
(4, 7)
(3, 5)
(4, 4)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None

   a  b  c  d  e  f  g  h
8  ♖  ♘  ♗  ♕  ♔  ♗  ♘  ♖
7  ♙  ♙  ♙        ♙  ♙  ♙
6
5
4              ♞
3        ♙
2  ♟  ♟           ♟  ♟  ♟
1  ♜     ♝  ♛  ♚  ♝  ♞  ♜

('d1',)
d 1
('d1',)
d 1
pos d1
piece =  ♛
finding moves for  4 1
5 1
(5, 1)
♚
3 1
(3, 1)
♝
4 2
(4, 2)

4 3
(4, 3)

4 4
(4, 4)

4 5
(4, 5)

4 6
(4, 6)

4 7
(4, 7)

4 8
(4, 8)
♕
(4, 1)
5 2
(5, 2)

6 3
(6, 3)

7 4
(7, 4)

8 5
(8, 5)

3 2
(3, 2)

2 3
(2, 3)

1 4
(1, 4)

[(4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (5, 2), (6, 3), (7, 4), (8, 5), (3, 2), (2, 3), (1, 4)]
d2
('d1',)
d 1
('d1',)
d 1
pos1 piece
d1 ♛
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)

8 3
(8, 3)

2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)

4 4
(4, 4)

4 3
(4, 3)

4 2
(4, 2)
♛
(4, 8)
5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)

2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

4 2
(4, 2)
♛
(3, 3)
2 2
(2, 2)
♟
(3, 3)
(4, 3)
(3, 7)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(1, 3)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 2)
(4, 5)
(5, 6)
(4, 8)
(3, 6)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 7)
(3, 5)
(4, 4)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)
d3
('d1',)
d 1
('d1',)
d 1
pos1 piece
d1 ♛
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)

8 3
(8, 3)

2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)

4 4
(4, 4)

4 3
(4, 3)
♛
(4, 8)
5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)

2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

4 2
(4, 2)

2 2
(2, 2)
♟
(3, 3)
(4, 3)
(3, 7)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(1, 3)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 2)
(4, 5)
(5, 6)
(4, 8)
(3, 6)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 7)
(3, 5)
(4, 4)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)
d4
('d1',)
d 1
('d1',)
d 1
pos1 piece
d1 ♛
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)

8 3
(8, 3)

2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)

4 4
(4, 4)
♛
(4, 8)
5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)

2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

4 2
(4, 2)

2 2
(2, 2)
♟
(3, 3)
(3, 7)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(1, 3)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 2)
(4, 5)
(5, 6)
(4, 8)
(3, 6)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 7)
(3, 5)
(4, 4)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)
d5
('d1',)
d 1
('d1',)
d 1
pos1 piece
d1 ♛
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)

8 3
(8, 3)

2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)
♛
(4, 8)
5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)

2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

4 2
(4, 2)

2 2
(2, 2)
♟
(3, 3)
(3, 7)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(1, 3)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 2)
(4, 5)
(5, 6)
(4, 8)
(3, 6)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 7)
(3, 5)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)
d6
('d1',)
d 1
('d1',)
d 1
pos1 piece
d1 ♛
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)

8 3
(8, 3)

2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)

4 6
(4, 6)
♛
(4, 8)
5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)
♛
(6, 8)
Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)
♛
(3, 7)
2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

4 2
(4, 2)

2 2
(2, 2)
♟
(3, 3)
(3, 7)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 2)
(5, 6)
(4, 8)
(3, 6)
(2, 7)
(6, 7)
(7, 6)
(4, 7)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)
d7
('d1',)
d 1
('d1',)
d 1
pos1 piece
d1 ♛
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)
♛
(3, 8)
2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)
♛
(4, 8)
5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)
♛
(5, 8)
7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)

2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

4 2
(4, 2)

2 2
(2, 2)
♟
(3, 3)
(3, 7)
(4, 6)
(5, 7)
(8, 6)
(2, 2)
(1, 6)
(1, 3)
(2, 8)
(7, 7)
(6, 8)
(4, 2)
(5, 6)
(4, 8)
(3, 6)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 7)
(3, 5)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)
d8
('d1',)
d 1
('d1',)
d 1
pos1 piece
d1 ♛
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)

8 3
(8, 3)

2 7
(2, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♛
(5, 8)
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)

2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

4 2
(4, 2)

2 2
(2, 2)
♟
(3, 3)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(1, 3)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 2)
(5, 6)
(4, 8)
(3, 6)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 7)
(3, 5)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 8)
e2
('d1',)
d 1
('d1',)
d 1
pos1 piece
d1 ♛
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)

8 3
(8, 3)

2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)

4 4
(4, 4)

4 3
(4, 3)

4 2
(4, 2)

4 1
(4, 1)

5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)

2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

4 2
(4, 2)

2 2
(2, 2)
♟
(3, 3)
(4, 3)
(3, 7)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(1, 3)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 2)
(4, 5)
(5, 6)
(4, 8)
(3, 6)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 1)
(4, 7)
(3, 5)
(4, 4)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)
f3
('d1',)
d 1
('d1',)
d 1
pos1 piece
d1 ♛
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)

8 3
(8, 3)

2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)

4 4
(4, 4)

4 3
(4, 3)

4 2
(4, 2)

4 1
(4, 1)

5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)

2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

4 2
(4, 2)

2 2
(2, 2)
♟
(3, 3)
(4, 3)
(3, 7)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(1, 3)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 2)
(4, 5)
(5, 6)
(4, 8)
(3, 6)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 1)
(4, 7)
(3, 5)
(4, 4)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)
g4
('d1',)
d 1
('d1',)
d 1
pos1 piece
d1 ♛
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)
♛
(3, 8)
2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)

4 4
(4, 4)

4 3
(4, 3)

4 2
(4, 2)

4 1
(4, 1)

5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)

2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

4 2
(4, 2)

2 2
(2, 2)
♟
(3, 3)
(4, 3)
(3, 7)
(4, 6)
(5, 7)
(8, 6)
(2, 2)
(1, 6)
(1, 3)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 2)
(4, 5)
(5, 6)
(4, 8)
(3, 6)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 1)
(4, 7)
(3, 5)
(4, 4)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)
h5
('d1',)
d 1
('d1',)
d 1
pos1 piece
d1 ♛
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)

8 3
(8, 3)

2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)

4 4
(4, 4)

4 3
(4, 3)

4 2
(4, 2)

4 1
(4, 1)

5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)

2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

4 2
(4, 2)

2 2
(2, 2)
♟
(3, 3)
(4, 3)
(3, 7)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(1, 3)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 2)
(4, 5)
(5, 6)
(4, 8)
(3, 6)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 1)
(4, 7)
(3, 5)
(4, 4)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)
c2
('d1',)
d 1
('d1',)
d 1
pos1 piece
d1 ♛
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)

8 3
(8, 3)

2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)

4 4
(4, 4)

4 3
(4, 3)

4 2
(4, 2)

4 1
(4, 1)

5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)

2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

4 2
(4, 2)

2 2
(2, 2)
♟
(3, 3)
(4, 3)
(3, 7)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(1, 3)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 2)
(4, 5)
(5, 6)
(4, 8)
(3, 6)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 1)
(4, 7)
(3, 5)
(4, 4)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)
b3
('d1',)
d 1
('d1',)
d 1
pos1 piece
d1 ♛
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)

8 3
(8, 3)

2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)

4 4
(4, 4)

4 3
(4, 3)

4 2
(4, 2)

4 1
(4, 1)

5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)

2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

4 2
(4, 2)

2 2
(2, 2)
♟
(3, 3)
(4, 3)
(3, 7)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(1, 3)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 2)
(4, 5)
(5, 6)
(4, 8)
(3, 6)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 1)
(4, 7)
(3, 5)
(4, 4)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)
a4
('d1',)
d 1
('d1',)
d 1
pos1 piece
d1 ♛
2 8
(2, 8)
♘
1 7
(1, 7)
♙
Knight moves:
2 8
(3, 10)
(4, 9)
(3, 6)
(0, 9)
(1, 10)
(4, 7)
(1, 6)
(0, 7)
4 7
(4, 7)

5 6
(5, 6)

6 5
(6, 5)

7 4
(7, 4)

8 3
(8, 3)

2 7
(2, 7)
♙
5 8
(5, 8)
♔
3 8
(3, 8)
♗
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)

4 4
(4, 4)

4 3
(4, 3)

4 2
(4, 2)

4 1
(4, 1)

5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
6 8
(6, 8)
♗
4 8
(4, 8)
♕
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

7 7
(7, 7)
♙
5 7
(5, 7)

4 6
(4, 6)

3 5
(3, 5)

2 4
(2, 4)

1 3
(1, 3)

Knight moves:
7 8
(8, 10)
(9, 9)
(8, 6)
(5, 9)
(6, 10)
(9, 7)
(6, 6)
(5, 7)
7 8
(7, 8)
♘
8 7
(8, 7)
♙
2 6
(2, 6)

0 6
(0, 6)
None
3 6
(3, 6)

1 6
(1, 6)

4 6
(4, 6)

2 6
(2, 6)

7 6
(7, 6)

5 6
(5, 6)

8 6
(8, 6)

6 6
(6, 6)

9 6
(9, 6)
None
7 6
(7, 6)

4 2
(4, 2)

2 2
(2, 2)
♟
(3, 3)
(4, 3)
(3, 7)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(1, 3)
(2, 8)
(7, 4)
(7, 7)
(6, 5)
(6, 8)
(4, 2)
(4, 5)
(5, 6)
(4, 8)
(3, 6)
(2, 4)
(2, 7)
(6, 7)
(7, 6)
(4, 1)
(4, 7)
(3, 5)
(4, 4)
(3, 8)
(8, 4)
(5, 8)
(8, 7)
(1, 7)
(2, 6)
(6, 6)
(7, 5)
(7, 8)
valid move
('d1',)
d 1
pos1 piece
d1 ♛
5 8
(5, 8)
♔
(4, 8)
3 8
(3, 8)
♗
(4, 8)
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)

4 4
(4, 4)

4 3
(4, 3)

4 2
(4, 2)

4 1
(4, 1)

5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
(4, 8)
Knight moves:
5 4
(6, 6)
(7, 5)
(6, 2)
(3, 5)
(4, 6)
(7, 3)
(4, 2)
(3, 3)
2 3
(2, 3)

0 3
(0, 3)
None
(4, 8)
3 3
(3, 3)
♙
(2, 2)
1 3
(1, 3)

(4, 8)
7 3
(7, 3)

5 3
(5, 3)

(4, 8)
8 3
(8, 3)

6 3
(6, 3)

(4, 8)
9 3
(9, 3)
None
7 3
(7, 3)

(4, 8)
2 1
(2, 1)

3 1
(3, 1)
♝
1 2
(1, 2)
♟
4 2
(4, 2)

5 3
(5, 3)

6 4
(6, 4)

7 5
(7, 5)

8 6
(8, 6)

2 2
(2, 2)
♟
6 1
(6, 1)
♝
4 1
(4, 1)

5 2
(5, 2)

5 0
(5, 0)
None
6 2
(6, 2)
♟
6 0
(6, 0)
None
4 2
(4, 2)

4 0
(4, 0)
None
7 2
(7, 2)
♟
5 2
(5, 2)

4 3
(4, 3)

3 4
(3, 4)

2 5
(2, 5)

1 6
(1, 6)

Knight moves:
7 1
(8, 3)
(9, 2)
(8, -1)
(5, 2)
(6, 3)
(9, 0)
(6, -1)
(5, 0)
7 1
(7, 1)
♞
8 2
(8, 2)
♟
(3, 4)
(4, 3)
(3, 1)
(3, 7)
(4, 6)
(5, 7)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(2, 5)
(1, 3)
(6, 2)
(7, 1)
(4, 2)
(4, 5)
(3, 3)
(5, 3)
(8, 2)
(1, 2)
(2, 1)
(6, 1)
(6, 4)
(7, 3)
(4, 1)
(4, 7)
(3, 5)
(5, 2)
(4, 4)
(3, 8)
(8, 4)
(5, 8)
(2, 3)
(7, 2)
(6, 6)
(7, 5)
(6, 3)

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None
/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None

   a  b  c  d  e  f  g  h
8  ♖  ♘  ♗  ♛  ♔  ♗  ♘  ♖
7  ♙  ♙  ♙        ♙  ♙  ♙
6
5
4              ♞
3        ♙
2  ♟  ♟           ♟  ♟  ♟
1  ♜     ♝     ♚  ♝  ♞  ♜

TypeError: game.get_moves() takes from 2 to 3 positional arguments but 4 were given

In [28]:
new_game.get_moves('e8')

('e8',)
e 8
pos e8
piece =  ♔
finding moves for  5 8
6 8
(6, 8)
♗
4 8
(4, 8)
♛
(5, 8)
5 9
(5, 9)
None
5 7
(5, 7)

6 9
(6, 9)
None
6 7
(6, 7)
♙
4 9
(4, 9)
None
4 7
(4, 7)

5 8
(5, 8)
♔
(4, 8)
3 8
(3, 8)
♗
(4, 8)
4 7
(4, 7)

4 6
(4, 6)

4 5
(4, 5)

4 4
(4, 4)

4 3
(4, 3)

4 2
(4, 2)

4 1
(4, 1)

5 7
(5, 7)

6 6
(6, 6)

7 5
(7, 5)

8 4
(8, 4)

3 7
(3, 7)
♙
(4, 8)
Knight moves:
5 4
(6, 6)
(7, 5)
(6, 2)
(3, 5)
(4, 6)
(7, 3)
(4, 2)
(3, 3)
2 3
(2, 3)

0 3
(0, 3)
None
(4, 8)
3 3
(3, 3)
♙
(2, 2)
1 3
(1, 3)

(4, 8)
7 3
(7, 3)

5 3
(5, 3)

(4, 8)
8 3
(8, 3)

6 3
(6, 3)

(4, 8)
9 3
(9, 3)
None
7 3
(7, 3)

(4, 8)
2 1
(2, 1)

3 1
(3, 1)
♝
1 2
(1, 2)
♟
4 2
(4, 2)

5 3
(5, 3)

6 4
(6, 4)

7 5
(7, 5)

8 6
(8, 6)

2 2
(2, 2)
♟
6 1
(6, 1)
♝
4 1
(4, 1)

5 2
(5, 2)

5 0
(5, 0)
None
6 2
(6, 2)
♟
6 0
(6, 0)
None
4 2
(4, 2)

4 0
(4, 0)
None
7 2
(7, 2)
♟
5 2
(5, 2)

4 3
(4, 3)

3 4
(3, 4)

2 5
(2, 5)

1 6
(1, 6)

Knight moves:
7 1
(8, 3)
(9, 2)
(8, -1)
(5, 2)
(6, 3)
(9, 0)
(6, -1)
(5, 0)
7 1
(7, 1)
♞
8 2
(8, 2)
♟
(1, 8)
(8, 8)
(6, 8)
(3, 8)
[(4, 8)]
d8
('e8',)
e 8
('e8',)
e 8
pos1 piece
e8 ♔
Knight moves:
5 4
(6, 6)
(7, 5)
(6, 2)
(3, 5)
(4, 6)
(7, 3)
(4, 2)
(3, 3)
2 3
(2, 3)

0 3
(0, 3)
None
3 3
(3, 3)
♙
(2, 2)
1 3
(1, 3)

7 3
(7, 3)

5 3
(5, 3)

8 3
(8, 3)

6 3
(6, 3)

9 3
(9, 3)
None
7 3
(7, 3)

2 1
(2, 1)

3 1
(3, 1)
♝
1 2
(1, 2)
♟
4 2
(4, 2)

5 3
(5, 3)

6 4
(6, 4)

7 5
(7, 5)

8 6
(8, 6)

2 2
(2, 2)
♟
6 1
(6, 1)
♝
4 1
(4, 1)

5 2
(5, 2)

5 0
(5, 0)
None
6 2
(6, 2)
♟
6 0
(6, 0)
None
4 2
(4, 2)

4 0
(4, 0)
None
7 2
(7, 2)
♟
5 2
(5, 2)

4 3
(4, 3)

3 4
(3, 4)

2 5
(2, 5)

1 6
(1, 6)

Knight moves:
7 1
(8, 3)
(9, 2)
(8, -1)
(5, 2)
(6, 3)
(9, 0)
(6, -1)
(5, 0)
7 1
(7, 1)
♞
8 2
(8, 2)
♟
(3, 4)
(4, 3)
(3, 1)
(4, 6)
(8, 3)
(8, 6)
(2, 2)
(1, 6)
(2, 5)
(1, 3)
(6, 2)
(7, 1)
(4, 2)
(3, 3)
(5, 3)
(8, 2)
(1, 2)
(2, 1)
(6, 1)
(6, 4)
(7, 3)
(4, 1)
(3, 5)
(5, 2)
(2, 3)
(7, 2)
(6, 6)
(7, 5)
(6, 3)

/Users/jaredlobo/Documents/GitHub/ChessApp/game_logic.py:27: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  self.last_move = None, None

['d8']

In [25]:
new_game.move(6,8,5,7)
display(new_game.board)
# new_game.get_moves(5,2, True)
# new_game.turn

TypeError: game.move() takes from 3 to 4 positional arguments but 5 were given

In [26]:
board = pd.DataFrame(columns=[1,2,3,4,5,6,7,8], index=reversed(range(8)))
print(board)

     1    2    3    4    5    6    7    8
7  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN